spring:

  messages:
    basename: static/i18n/messages

  datasource:
    url: jdbc:mysql://localhost:3306/lsl?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/page/
      suffix: .jsp

    static-path-pattern: /scripts/**


    hiddenmethod:
      filter:
        enabled: true


  web:
    resources:
      static-locations: classpath:/scripts/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yr.entity




