spring:
  #???

#  datasource:
#    jndi-name: aa

  datasource:
    url: jdbc:mysql://localhost:3306/hh?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


  #freemarker
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: ctx
    suffix: .ftlh

  mvc:
    hiddenmethod:
      filter:
        enabled: true








